name: 'Setup Environment'
description: 'Sets up the environment for the project'

inputs: {}

runs:
  using: 'composite'
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - uses: pnpm/action-setup@v2
      name: Install pnpm
      id: pnpm-install
      with:
        version: 7
        run_install: false

    - name: Print node/pnpm versions
      shell: bash
      id: versions
      run: |
        node_ver=$( node --version )
        pnpm_ver=$( pnpm --version || true )

        echo "Node: ${node_ver:1}"
        if [[ $pnpm_ver != '' ]]; then echo "PNPM: $pnpm_ver"; fi

        echo "node_version=${node_ver:1}" >> $GITHUB_OUTPUT

    - name: Get pnpm cache directory path
      shell: bash
      id: pnpm-cache-dir-path
      run: echo "dir=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Use the node_modules cache if available [pnpm]
      id: cache-node-modules-pnpm
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-node-${{ steps.versions.outputs.node_version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ steps.versions.outputs.node_version }}-

    - name: Cache Cypress binary
      uses: actions/cache@v3
      id: cache-cypress-binary
      with:
        path: ~/.cache/Cypress
        key: cypress-${{ runner.os }}-cypress-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          cypress-${{ runner.os }}-cypress-

    - name: Install dependencies
      shell: bash
      run: pnpm install

    - name: Install Cypress binary if no cache hit
      shell: bash
      if: steps.cache-cypress-binary.outputs.cache-hit != 'true'
      run: pnpm cypress install

    - name: Get Playwright browsers cache directory path
      shell: bash
      id: playwright-cache-dir-path
      run: echo "dir=$(pnpm config get cache)/ms-playwright" >> $GITHUB_OUTPUT

    - name: Cache Playwright browsers
      id: cache-playwright-browsers
      uses: actions/cache@v3
      with:
        path: ${{ steps.playwright-cache-dir-path.outputs.dir }}
        key: playwright-browsers-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          playwright-browsers-${{ runner.os }}-

    - name: Install Playwright browsers if no cache hit
      shell: bash
      if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
      run: pnpm playwright install

